---
galaxy_info:
  role_name: ssh_hardening
  namespace: pearlab0x
  author: pearlab0x
  description: Deploys a hardened sshd_config with validation and safe restart
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - ssh
    - hardening

dependencies: []
